import "@/styles/globals.css";

import { Inter } from "next/font/google";
import { headers } from "next/headers";
import * as content from "next/headers"

import { TRPCReactProvider } from "@/trpc/react";
import Header from "@/app/_components/header";
import { auth, getPageSession } from "@/server/lucia";
import { get } from "http";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <link
        rel="stylesheet"
        href="https://unpkg.com/leaflet@1.8.0/dist/leaflet.css"
        integrity="sha512-hoalWLoI8r4UszCkZ5kL8vayOGVae1oxXe/2A4AO6J9+580uKHDO3JdHb7NzwwzK5xr/Fs0W40kiNHxM9vyTtQ=="
        crossOrigin=""
      />
      <body className={`font-sans ${inter.variable}`}>
        <TRPCReactProvider headers={headers()}>
          <RootLayoutView>{children}</RootLayoutView>
        </TRPCReactProvider>
      </body>
    </html>
  );
}


export function RootLayoutView({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
  <main className="">
  <Header />
  {children} 
  </main>)
}